### ISSUE TITLE
No setting for "Run on Startup"

### ISSUE THREAD

**Issue by yujioshiro** [Kyome22/menubar_runcat#12]
Currently using the App Store version.

There is no option to Run on Startup. I have to open runcat every time I start (or restart) my computer.

**Comment by Kyome22** [comment]
@yujioshiro I don't accept inquiries about AppStore versions on GitHub.

If you have macOS 13 or higher, you can specify that RunCat will start automatically when you login to mac.

<img width="431" alt="Screenshot 2023-07-30 at 15 00 52" src="https://github.com/Kyome22/menubar_runcat/assets/19896354/2dede688-6685-4125-9b9e-6da3dc70fd5f">

**Comment by yujioshiro** [comment]
Thank you! I will need to update my mac then
