### ISSUE TITLE
Non-retina display issue

### ISSUE THREAD

**Issue by heller** [Kyome22/menubar_runcat#2]
Hi, thank you for RunCat.

I just updated to version 4.7 via the App Store, and it seems that the 2x/retina images are being shown on my non-retina Macbook Air. Instead of the full image, only the top left quadrant is shown. I tried quitting and reopening the app, and will try rebooting soon.

**Comment by Kyome22** [comment]
Hi, heller.

I fixed the problem and released version 4.7.1 via the App Store. Do you know?

**Comment by heller** [comment]
Yes! Thank you very much.
