### ISSUE TITLE
0gb disk info

### ISSUE THREAD

**Issue by ciaosonokekko** [Kyome22/menubar_runcat#3]
Hi, i've bought the runCat App, it is amazing and so cute! 
In the last 2 days it started to say 0gb of free disk, but i have about 100gb free. 
I've tried to delete all, library file too, and install it again, but nothing looks like to change.

Can someone help me?
Thank you in advance

**Comment by ciaosonokekko** [comment]
no news?

**Comment by Kyome22** [comment]
Hi.
Do you set the primary language to French?

**Comment by Kyome22** [comment]
> Hi, i've bought the runCat App, it is amazing and so cute!
> In the last 2 days it started to say 0gb of free disk, but i have about 100gb free.
> I've tried to delete all, library file too, and install it again, but nothing looks like to change.
> 
> Can someone help me?
> Thank you in advance

Hi.
Do you set the primary language to French?

**Comment by ciaosonokekko** [comment]
> > Hi, i've bought the runCat App, it is amazing and so cute!
> > In the last 2 days it started to say 0gb of free disk, but i have about 100gb free.
> > I've tried to delete all, library file too, and install it again, but nothing looks like to change.
> > Can someone help me?
> > Thank you in advance
> 
> Hi.
> Do you set the primary language to French?

Hi,
nope, my primary and only language is English.

**Comment by Kyome22** [comment]
> > > Hi, i've bought the runCat App, it is amazing and so cute!
> > > In the last 2 days it started to say 0gb of free disk, but i have about 100gb free.
> > > I've tried to delete all, library file too, and install it again, but nothing looks like to change.
> > > Can someone help me?
> > > Thank you in advance
> > 
> > 
> > Hi.
> > Do you set the primary language to French?
> 
> Hi,
> nope, my primary and only language is English.

I'm using the following code.
I could not find the bug... hmm

```swift
struct DiskInfo {
    var value: Double = 0.0
    var indicator: String = "0.0 GB"
    var indicatorRect: String = "▁"
    var percentage: String = "Disk: 0.0%"
    var capacity: String = "0.0 GB free out of 0.0 GB"
    
    init() {}
    
    init(value: Double, indicator: String, percentage: String, capacity: String) {
        self.value = value
        self.indicator = indicator
        self.indicatorRect = String(percentage: value)
        self.percentage = percentage
        self.capacity = capacity
    }
}

class Disk {
    
    func statistics() -> DiskInfo {
        let url = NSURL(fileURLWithPath: "/")
        let keys: [URLResourceKey] = [.volumeTotalCapacityKey, .volumeAvailableCapacityForImportantUsageKey]
        guard let dict = try? url.resourceValues(forKeys: keys) else {
            return DiskInfo()
        }
        let total = (dict[URLResourceKey.volumeTotalCapacityKey] as! NSNumber).int64Value
        let free = (dict[URLResourceKey.volumeAvailableCapacityForImportantUsageKey] as! NSNumber).int64Value
        let used: Int64 = total - free
        
        let value: Double = min(99.9, round(1000.0 * Double(used) / Double(total)) / 10.0)
        let fmt = ByteCountFormatter()
        fmt.countStyle = .decimal
        // support french style 3,14 → 3.14
        let totalStr = fmt.string(fromByteCount: total).replacingOccurrences(of: ",", with: ".")
        let freeStr = fmt.string(fromByteCount: free).replacingOccurrences(of: ",", with: ".")
       
        let freeArray = freeStr.components(separatedBy: CharacterSet.whitespaces)
        let freeValue = Int((Double(freeArray[0]) ?? 0.0).rounded())
        
        return DiskInfo(
            value: value,
            indicator: "\(freeValue) \(freeArray[1])",
            percentage: "Disk: \(value)%",
            capacity: "\(freeStr) free out of \(totalStr)"
        )
    }
    
}
```

**Comment by ciaosonokekko** [comment]
Hi! I just updated the app from the AppStore and I can confirm it solves the problem. I'm Italian, not french, by the way 😄
